version: '3.8'

services:
  app:
    build: .
    container_name: ml-fastapi-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn api.app:app --host 0.0.0.0 --port 8000 --reload

  test:
    build: .
    command: pytest
    volumes:
      - .:/app

